<center>
    <h1 style="color:blue"> YSU MMF, Python, Spring 2021 </h1>
    <h2 style="color:blue"> Lecture 19 </h2>
</center>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Numpy linalg package

- Calculate the dot product of two 1D arrays

In [3]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [4]:
b = np.array([1,0,2,-2,1])

In [5]:
a*b

array([ 0,  0,  4, -6,  4])

In [6]:
np.sum(a*b)

2

In [7]:
np.dot(a,b)

2

In [9]:
a.dot(b)

2

- Calculate the $l_1$,  $l_2$ and $l_\infty$ norms of a 1D array

In [11]:
np.linalg.norm(a, ord=np.inf)

4.0

- Calculate the Matrix product of two matrices

In [13]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
b = np.random.randint(low = 1, high = 10, size = (4,4))
b

array([[1, 4, 7, 3],
       [1, 2, 1, 9],
       [6, 2, 2, 9],
       [1, 8, 1, 3]])

In [15]:
np.dot(a,b)

array([[ 16,  30,   8,  36],
       [ 52,  94,  52, 132],
       [ 88, 158,  96, 228],
       [124, 222, 140, 324]])

- Calculate the Inverse of a square matrix, and show that it is indeed the inverse of that matrix 

In [27]:
a = np.arange(16).reshape(4,4)
b = np.linalg.inv(a)
b

array([[ 9.00719925e+14, -4.50359963e+14, -1.80143985e+15,
         1.35107989e+15],
       [-2.40191980e+15,  2.70215978e+15,  1.80143985e+15,
        -2.10167983e+15],
       [ 2.10167983e+15, -4.05323966e+15,  1.80143985e+15,
         1.50119988e+14],
       [-6.00479950e+14,  1.80143985e+15, -1.80143985e+15,
         6.00479950e+14]])

In [28]:
np.dot(a,b)

array([[ 1.25 , -0.5  ,  0.5  , -0.125],
       [ 0.25 ,  1.5  , -1.5  , -0.125],
       [-1.25 ,  3.5  ,  0.5  ,  0.375],
       [-2.25 ,  1.5  , -1.5  ,  0.875]])

- Find the rank of a matrix

In [29]:
np.linalg.matrix_rank(a)

2

- Calculate the determinant of the matrix

In [30]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
np.linalg.det(a)

-2.9582283945787796e-30

- Find the Eigenvalues and Eigenvectors of a matrix

In [32]:
np.linalg.eig(a)

(array([ 3.24642492e+01, -2.46424920e+00,  1.92979794e-15, -4.09576009e-16]),
 array([[-0.11417645, -0.7327781 ,  0.54500164,  0.00135151],
        [-0.3300046 , -0.28974835, -0.68602671,  0.40644504],
        [-0.54583275,  0.15328139, -0.2629515 , -0.8169446 ],
        [-0.76166089,  0.59631113,  0.40397657,  0.40914805]]))

In [33]:
a = np.array([[3,1],[2,2,]])

In [34]:
lam, v = np.linalg.eig(a)

In [35]:
lam

array([4., 1.])

In [36]:
v

array([[ 0.70710678, -0.4472136 ],
       [ 0.70710678,  0.89442719]])

- Solve a System of Linear Equations 
$$
A\cdot x = b
$$

- Find the Singular Value Decomposition (SVD) for a matrix $A$

- Explore also the Linear Algebra package of `scipy`: [https://docs.scipy.org/doc/scipy/reference/linalg.html](https://docs.scipy.org/doc/scipy/reference/linalg.html)

# Working with Polynomials

- Find the value of the polynomial 
$$
P(x) = 2x^2 + 3x - 1
$$
at $x=2$

- Find the roots of the above polynomial

- Construct the Best fitting 1st, 2nd and 3rd order polynomials for the data
$$
(0,1); (2, -1); (3, 0); (-1, 4)
$$
Visualise the result.

- Construct the Least Squares Polynomial Fitting some data.Visualize the dataset and the fitting line

- Explore other functions in [https://numpy.org/doc/stable/reference/routines.polynomials.html](https://numpy.org/doc/stable/reference/routines.polynomials.html)

# Further possibilities of Numpy

- Sort a ndarray

- Use `argmax`, `argmin`, `where`, `extract` - see [https://numpy.org/doc/stable/reference/routines.sort.html](https://numpy.org/doc/stable/reference/routines.sort.html)